image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test
  - deploy

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"

before_script:
  - export PATH="$PATH:/root/.dotnet/tools"
  - dotnet restore

build:
  stage: build
  script:
    - dotnet build --configuration Release

test:
  stage: test
  script:
    - dotnet build TestControllers/TestControllers.csproj --configuration Release
    - dotnet test TestControllers/TestControllers.csproj --configuration Release --no-build --verbosity normal

deploy:
  stage: deploy
  script:
    - docker build -t ordersystem-app .
    - docker run -d -p 5000:80 --name ordersystem-app ordersystem-app
