stages:
  - build
  - test
  - deploy

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet build OrderSystemV1/OrderSystemV1.csproj --configuration Release
  artifacts:
    paths:
      - OrderSystemV1/

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet build TestControllers/TestControllers.csproj --configuration Release
    - dotnet test TestControllers/TestControllers.csproj --configuration Release --no-build --verbosity normal
  artifacts:
    paths:
      - OrderSystemV1/

deploy:
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
  script:
    - pwd
    - ls -l OrderSystemV1/
    - cat OrderSystemV1/Program.cs
    - docker rm -f ordersystem-app || true
    - docker build -t ordersystem-app -f OrderSystemV1/Dockerfile OrderSystemV1
    - docker run -d -p 5000:80 --name ordersystem-app -e ConnectionStrings__DefaultConnection="Host=host.docker.internal;Port=5432;Database=clientsorders;Username=postgres;Password=1234" ordersystem-app