build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet build OrderSystemV1/OrderSystemV1.csproj --configuration Release
  artifacts:
    paths:
      - OrderSystemV1/

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet build TestControllers/TestControllers.csproj --configuration Release
    - dotnet test TestControllers/TestControllers.csproj --configuration Release --no-build --verbosity normal
  artifacts:
    paths:
      - OrderSystemV1/

deploy:
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
  script:
    - docker rm -f ordersystem-app || true
    - docker build -t ordersystem-app .
    - docker run -d -p 5000:80 --name ordersystem-app ordersystem-app