stages:
  - build
  - test
  - deploy

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet build --configuration Release

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet build TestControllers/TestControllers.csproj --configuration Release
    - dotnet test TestControllers/TestControllers.csproj --configuration Release --no-build --verbosity normal

deploy:
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock  
  script:
    - docker rm -f ordersystem-app || true
    - docker build -t ordersystem-app -f OrderSystemV1/Dockerfile OrderSystemV1
    - docker run -d -p 5000:80 --name ordersystem-app ordersystem-app
