image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/

stages:
  - build
  - test
  - deploy

before_script:
  - apk add --no-cache curl
  - docker info

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet build --configuration Release

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet build TestControllers/TestControllers.csproj --configuration Release
    - dotnet test TestControllers/TestControllers.csproj --configuration Release --no-build --verbosity normal

deploy:
  stage: deploy
  script:
    - docker rm -f ordersystem-app || true
    - docker build -t ordersystem-app .
    - docker run -d -p 5000:80 --name ordersystem-app ordersystem-app
