stages:
  - build
  - test
  - deploy

variables:
  PROJECT_NAME: "OrderSystemV1"
  DOCKER_HOST: "tcp://docker:2375"  

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet restore
    - dotnet build --configuration Release
  artifacts:
    paths:
      - $PROJECT_NAME/bin/Release/net8.0/

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: "OrderSystem"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=clientsorders;Username=postgres;Password=123456789"
  script:
    - dotnet test --no-build --verbosity normal

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t ordersystem .
    - docker run -d -p 5000:8080 --name ordersystem_app ordersystem
  only:
    - main